###
POST http://localhost:8080/api/1.0/login?username=b&password=b
Content-Type: application/json

> {%
 client.global.set("token",response.body.access)
%}

###
POST http://localhost:8080/api/1.0/verify_location
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ueid": {
    "msisdn": "+34649379033",
    "ipv4Addr": "195.55.210.1"
  },
  "latitude": 40.51631448474623,
  "longitude": -3.6641764039585074,
  "accuracy": 2
}