###
POST http://localhost:8080/api/1.0/login
Content-Type: application/json

{
  "username": "b",
  "password": "b"
}

> {%
 client.global.set("token",response.body.access)
%}

### 40.51559498031505, -3.6621088484636917 buenas
### 40.41682, -3.68473 malas
POST http://localhost:8080/api/1.0/verify_location
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ueid": {
    "msisdn": "+34649379033"
  },
  "latitude": 40.41682,
  "longitude": -3.68473,
  "accuracy": 2
}