###
POST http://localhost:8080/api/1.0/login?username=b&password=b
Content-Type: application/json

> {%
 client.global.set("token",response.body.access)
%}

###
POST http://localhost:8080/api/1.0/verify_location
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ueid": {
    "msisdn": "+34649379033"
  },
  "latitude": 40.4525075099974,
  "longitude": -3.7972401929128146,
  "accuracy": 2
}