###
POST http://localhost:8080/login?username=b&password=b
Content-Type: application/json

> {%
    client.global.set("token", response.body.access);
%}

###
POST http://localhost:8080/qod/sessions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "device": {
    "phoneNumber": "+34649379033",
    "ipv4Address": {
      "publicAddress": "185.167.210.42",
      "privateAddress": "185.167.210.42"
    }
  },
  "applicationServer": {
    "ipv4Address": "192.168.1.100"
  },
  "qosProfile": "HIGH_BW",
  "webhook": {
    "notificationUrl": "https://cuatro.studio/ogw/callback"
  },
  "duration": 600,
  "asId": "summerhackaton-app"
}

> {%
    client.test("Sesión creada", function() {
        client.assert(response.status === 201, "Error al crear sesión: " + response.status);
        if (response.status === 201) {
            client.global.set("session_id", response.body.sessionId);
        }
    });
%}