###
POST http://localhost:8080/login?username=b&password=b
Content-Type: application/json

> {%
    client.global.set("token", response.body.access);
%}
###
POST http://localhost:8080/qod/sessions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "externalSessionId": "session_test_2024",
  "ueId": {
    "msisdn": "+34649379033",
    "ipAddress": "185.167.210.42"
  },
  "qosProfile": "HIGH_BW",
  "notificationUrl": "https://cuatro.studio/ogw/callback",
  "duration": 600,
  "asId": "summerhackaton-app"
}