###
POST http://localhost:8080/api/1.0/login
Content-Type: application/json

{
  "username": "b",
  "password": "b"
}

> {%
    client.global.set("token",response.body.access)
%}

###
POST http://localhost:8080/api/1.0/sessions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "device": {
    "phoneNumber": "+34649379033"
  },
  "applicationServer": {
    "ipv4Address": "10.19.249.233/16"
  },
  "qosProfile": "QOS_L",
  "duration": 86400
}